name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v6

    - name: install crosstool
      run: apt install crosstool-ng

    - name: configure crosstool
      run: ct-ng sparc-unknown-linux-gnu

